### PR TITLE
chore: start migration to effect/io 0.1

### PR DESCRIPTION
**Pull request by tim-smart**

### CODE REVIEW

**Comment by tim-smart** [comment]
@IMax153 Wasn't sure what to replace `getCallTrace` with - I'm not too familiar with how the tracing works.

**Comment by IMax153** [comment]
@tim-smart - thanks for starting work on this! Honestly, tracing is a bit tedious. The handling of traced regions with the new setup in `@effect/io`, while powerful, can be a bit hard to wrap your head around (it was for me).

I'd suggest if you want to continue on this, that we sync up tomorrow (perhaps with @mikearnaldi) to discuss.

**Comment by tim-smart** [comment]
> @tim-smart - thanks for starting work on this! Honestly, tracing is a bit tedious. The handling of traced regions with the new setup in `@effect/io`, while powerful, can be a bit hard to wrap your head around (it was for me).
> 
> I'd suggest if you want to continue on this, that we sync up tomorrow (perhaps with @mikearnaldi) to discuss.

Yeah that could be good.

For now I have just replaced getCallTrace with the Debug.*WithTrace functions.

You probably will want to add dual's at some point and add tracing to more operators?

**Comment by patroza** [comment]
@mikearnaldi can you have a look please, so we can merge this for a preliminary 0.1 release that at least works with latest effect?

**Comment by mikearnaldi** [comment]
Merging this for the crowd's request, but for a real release there is lots of work to do:
- internals should be untraced
- tracing regions should be restored on function inputs
- potentially channel should be tracing on its own

**Pull request merged**
